version: "3"
services:
  web:
    build:
      dockerfile: ./app.dockerfile
      context: .
    container_name: uhtred-web
    image: leandronsp/uhtred-web
    ports:
      - "8080:8080"
    environment:
      - API_HOST=localhost
      - API_PORT=4000
    command: >
      bash -c "npm run build && npm run server:dev"
  tdd:
    build:
      dockerfile: ./app.dockerfile
      context: .
    volumes:
      - "./app:/var/www/app"
    command: >
      bash -c "npm run tdd"
